- name: Añadir el modulo br_netfilter
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Activar masquerade en el firewall
  ansible.posix.firewalld:
    masquerade: yes
    state: enabled
    permanent: yes

- name: Recargar reglas de firewall
  shell:
    cmd: firewall-cmd --reload

- name: Permitir a kubernetes manejar el trafico con el firewall
  blockinfile:
    path: /etc/sysctl.d/k8s.conf
    create: yes
    block: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1

- name: Aplicar los cambios en sistema
  shell:
    cmd: sysctl --system
  