- name: Descargamos el fichero de configuración de cilium
  get_url:
    url: https://raw.githubusercontent.com/cilium/cilium/v1.9/install/kubernetes/quick-install.yaml
    dest: /tmp/custom-resources.yaml

- name: Reemplazar cidr
  lineinfile:
    path: /tmp/custom-resources.yaml
    regexp: "cluster-pool-ipv4-cidr:"
    line: "  cluster-pool-ipv4-cidr: {{ cidr_ip }}"

- name: Instalar cilium
  shell:
    cmd: kubectl apply -f /tmp/custom-resources.yaml