- name: Configurar puertos trafico para kubernetes
  ansible.posix.firewalld:
    port: "{{ item }}"
    zone: public
    permanent: yes
    state: enabled
  loop: "{{ firewall_ports }}"

- name: Recargar reglas de firewall
  shell:
    cmd: firewall-cmd --reload
