- name: install packages
  dnf:
    name: "{{ rpms_nfs }}"
    state: latest
  become: yes

- name: Arrancar servicio nfs
  systemd:
    name: nfs-server
    state: started
    enabled: yes
    masked: no
  become: yes